### ISSUE TITLE
rework vision

### ISSUE THREAD

**Issue by linglejack06** [team401/coppercore#29]
Summary: create a useful vision system across years
- read Photon Vision docs thoroughly
- add basic example and test
- if needed, add more advanced standard deviations and pose rejections (after testing basic)

**Comment by linglejack06** [comment]
@aidnem youre just a placeholder here, just figured i would start creating issues while i had time

**Comment by aidnem** [comment]
@linglejack06 Sounds good.  I've been reading photon docs and I will continue so I can gladly take some of the issues and I can also create some.
Not sure if you saw but the retro doc is on the controls drive so we should create a comment on each item of the doc that we create an issue for so that we don't create duplicate tickets.

**Comment by aidnem** [comment]
I'm going to break this issue down into smaller issues so we can work more incrementally

**Comment by aidnem** [comment]
Created and worked on #30

**Comment by linglejack06** [comment]
@jkleiber @aidnem why have we never tried using limelight rather than photon vision? a lot of the code seems simpler to incorporate

**Comment by jkleiber** [comment]
@linglejack06 a single limelight costs $400 while we can get 4 cameras and a beelink for a similar price. The cameras on the limelight are very similar to the ones we have as well

Theoretically we should be able to get better coverage with multiple cameras. The advantage of limelight is that they do most of the work for users, which is why it is more expensive and why the code is easier

**Comment by linglejack06** [comment]
Yeah, I just figured with how much difficulty we’ve had with vision it might be looking into if we still can’t figure vision out Sent from my iPhoneOn Nov 22, 2024, at 6:06 PM, Justin Kleiber ***@***.***> wrote:﻿
@linglejack06 a single limelight costs $400 while we can get 4 cameras and a beelink for a similar price. The cameras on the limelight are very similar to the ones we have as well
Theoretically we should be able to get better coverage with multiple cameras. The advantage of limelight is that they do most of the work for users, which is why it is more expensive and why the code is easier

**Comment by avidraccoon** [comment]
They also sell one for 200
